---
# ====== Application: PC Garage ==============================
identification: 
  name: PC Garage
  alias: PC-GARAGE
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: false
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 40873232398861600528

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: WKSP_LABBDPAULHONDOLA

globalization: 
  primary-language: English (en)
  document-direction: Language Default
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: PC Garage

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 40873233153972600529

navigation-bar: 
  implementation: List
  list: Navigation Bar # 40873234345966600531
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 15623651161989

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: PC Garage

component-settings: 
- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 40873227771648600524
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 15623458853157

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 40873228091248600525
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 15623458853254

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 40873228321989600525
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 15623458853283

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 40873228742883600525
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 15623458853305

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 40873229095302600525
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 15623458853323

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 40873229308575600526
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 15623458853333

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 40873229684297600526
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 15623458853354

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 40873229992662600526
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 15623458853381

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 40873230212351600526
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 15623458853393

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 40873230592988600526
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 15623458853408

- # ====== Component Setting: NATIVE_IR ========================
  id: 40873230860077600527
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 15623458853429

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 40873231189088600527
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 15623458853450

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 40873231482851600527
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 15623458853466

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 40873231795872600527
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 15623458853481

